"""initial

Revision ID: 2dcfc2ce13cb
Revises:
Create Date: 2025-08-25 11:09:23.822833

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dcfc2ce13cb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "school",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_school_id"), "school", ["id"], unique=False)
    op.create_table(
        "classroom",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["school_id"], ["school.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_classroom_id"), "classroom", ["id"], unique=False)
    op.create_table(
        "user_account",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_student", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["school_id"], ["school.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_user_account_id"), "user_account", ["id"], unique=False)
    op.create_table(
        "classroom_user_account_table",
        sa.Column("classroom_id", sa.Integer(), nullable=False),
        sa.Column("user_account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["classroom_id"], ["classroom.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_account_id"], ["user_account.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("classroom_id", "user_account_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classroom_user_account_table")
    op.drop_index(op.f("ix_user_account_id"), table_name="user_account")
    op.drop_table("user_account")
    op.drop_index(op.f("ix_classroom_id"), table_name="classroom")
    op.drop_table("classroom")
    op.drop_index(op.f("ix_school_id"), table_name="school")
    op.drop_table("school")
    # ### end Alembic commands ###
