"""create initial tables

Revision ID: c6cb385c78f2
Revises:
Create Date: 2025-08-18 12:58:42.701590

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c6cb385c78f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
